services:

  database:
    image: mysql:latest-alphine
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE="magazine"
      - MYSQL_HOST="database"
      - MYSQL_ROOT_PASSWORD="9goFK18O7XNFZI"
    volumes:
      - init
    networks:
      - backend

networks:
  backend:
    name: backend-network

volumes:
   init:
     name: dbInit
     mount: 
        source: server/initTables.sql
        destination: docker-entrypoint-initdb.d/initTables.sql
    