services:
  backend:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8443:8443
    networks:
      - backend-network


  nginx:
    container_name: nginx
    depends_on:
      - backend
    build:      
      context: /nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge




